#revision tags must be an INTEGER value
#will search for .txt files having $Revision: $rev $ 
#and will replace $rev by the corresponding autogenerated revision 
#resulting in something like $Revision: 156 $ a subversion style xD
#you can create a git alias to call in this way:
#git revision "HERE GOES YOUR COMMENT"

export tag=`git tag | sort -n | tail -1`

text=`echo $tag | sed "s/\([^0-9]*\)\([0-9]*\)/\1/"` ;
num=`echo $tag | sed "s/\([^0-9]*\)\([0-9]*\)/\2/"` ;
rev=`echo $text$(($num + 1))`

find ./ -name "*.txt" -type f | while read file
do
    awk '{gsub(/\$Revision:(.*)\$/, "$Revision: '$rev' $"); print}' $file >$file.$$
	mv -v $file.$$ $file
done
echo "Current revision: $tag"
echo "Next revision: $rev"
echo $@ 
git commit -am "$1" && git tag -a $rev -m "$1"
